log:
  level: debug

ssh:
  listen: "0.0.0.0:2222"
  hostkeys:
    - /etc/containerssh/ssh_host_rsa_key

auth:
  url: "http://auth:8080/auth"
  timeout: 30s

configserver:
  url: "http://configserver:8080/config"
  timeout: 30s

backend: docker

docker:
  connection:
    host: unix:///var/run/docker.sock
  
  execution:
    mode: session
    
    container:
      image: "alpine:latest" 
      workingDir: /root
      network:
        enabled: false