{"timestamp":"2025-12-15T13:53:30Z","level":"crit","code":"CORE_CONFIG_ERROR","message":"Invalid configuration in file /config.yaml (open /config.yaml: no such file or directory)","details":{"module":"core"}}
