services:
  auth:
    build: ./auth-server
    ports:
      - "8081:8080"
    networks:
      - containerssh-network

  config:
    build: ./config-server
    ports:
      - "8082:8080"
    networks:
      - containerssh-network

  containerssh:
    image: containerssh/containerssh:latest
    ports:
      - "2222:2222"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/etc/containerssh/config.yaml
      - ./ssh_host_rsa_key:/etc/containerssh/ssh_host_rsa_key
    depends_on:
      - auth
      - config
    networks:
      - containerssh-network

networks:
  containerssh-network:
    driver: bridge
