apiVersion: v1
kind: Service
metadata:
  name: containerssh-service
  namespace: default
spec:
  selector:
    app: containerssh
  ports:
  - port: 2222
    targetPort: 2222
    nodePort: 30022
  type: NodePort
